image: 608395931184.dkr.ecr.us-east-1.amazonaws.com/ci/centos/nodejs-10-centos7

stages:
  - build
  - deploy

.app_build_template: &app_job_definition
  stage: build
  tags:
    - design
  script:
    - npm install && npm run deploy
  artifacts:
    expire_in: 24 hrs
    paths:
      - dist

.app_deploy_template: &app_deploy_definition
  image: 608395931184.dkr.ecr.us-east-1.amazonaws.com/ci/python-aws-cli:latest
  stage: deploy
  when: manual
  tags:
    - design
  script:
    ## Create tarball of whole project for people who want to install tar as npm
    - tar --exclude=./node_modules --exclude=./dist --exclude=./.gitlab-ci.yml --exclude-vcs -czf ../project.tar.gz .

    ## Copy tarball of entire project package to a versioned folder
    - aws s3 cp ../project.tar.gz s3://${S3_DEPLOY_BUCKET}/${CI_PROJECT_NAME}/pkg/${CI_COMMIT_TAG}/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.gz

    ## Copy only minified CSS to a versioned folder
    - aws s3 sync ./css s3://${S3_DEPLOY_BUCKET}/${CI_PROJECT_NAME}/css/${CI_COMMIT_TAG}/

    ## Replace existing fonts folder with current fonts (this should not actually change files and is more a precaution)
    - aws s3 sync ./fonts s3://${S3_DEPLOY_BUCKET}/${CI_PROJECT_NAME}/fonts --delete

.app_dev_conditions: &app_dev_condition_def
  only:
    refs:
      - develop
      - merge_requests
  except:
    refs:
      - branches
      - master
  variables:
    S3_DEPLOY_BUCKET: "${STAGE_S3_DEPLOY_BUCKET}"

.app_prod_conditions: &app_prod_condition_def
  only:
    refs:
      - tags
      - master
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
  except:
    refs:
      - branches
      - develop
  variables:
    S3_DEPLOY_BUCKET: "${PROD_S3_DEPLOY_BUCKET}"

build:dev:
  <<: *app_job_definition
  <<: *app_dev_condition_def

build:prod:
  <<: *app_job_definition
  <<: *app_prod_condition_def

deploy:dev:
  <<: *app_deploy_definition
  <<: *app_dev_condition_def
  dependencies:
    - build:dev

deploy:prod:
  <<: *app_deploy_definition
  <<: *app_prod_condition_def
  dependencies:
    - build:prod
